/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MKV58F1M0xxx24
package_id: MKV58F1M0VLL24
mcu_data: ksdk2_0
processor_version: 6.0.1
pin_labels:
- {pin_num: '26', pin_signal: HSADC0A_CH4/CMP1_IN5/CMP0_IN5/PTE29/FTM0_CH2/FTM_CLKIN0, label: STEP_OUT, identifier: STEP_OUT;M_STEP}
- {pin_num: '27', pin_signal: DAC0_OUT/CMP1_IN3/HSADC0A_CH5/PTE30/FTM0_CH3/FTM_CLKIN1, label: M_DIR, identifier: M_DIR}
- {pin_num: '31', pin_signal: HSADC0B_CH4/HSADC1B_CH4/PTE24/CAN1_TX/FTM0_CH0/XB_IN2/I2C0_SCL/EWM_OUT_b/XB_OUT4/UART4_TX, label: M_RES, identifier: M_RES}
- {pin_num: '32', pin_signal: HSADC0B_CH5/HSADC1B_CH5/PTE25/LLWU_P21/CAN1_RX/FTM0_CH1/XB_IN3/I2C0_SDA/EWM_IN/XB_OUT5/UART4_RX, label: M_SLEEP, identifier: M_SLEEP}
- {pin_num: '35', pin_signal: PTA1/UART0_RX/FTM0_CH6/CMP0_OUT/FTM2_QD_PHA/FTM1_CH1/JTAG_TDI, label: M_e, identifier: M_e;M_EN}
- {pin_num: '94', pin_signal: HSADC1A_CH11/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FTM0_CH1/FLEXPWM0_B0/FB_CS0_b/FLEXPWM1_B0, label: OVER_T, identifier: OVER_T}
- {pin_num: '99', pin_signal: HSADC1A_CH9/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FTM1_CH0/FTM0_FLT0/SPI1_SOUT/FB_AD0, label: DRV_OFF, identifier: DRV_OFF}
- {pin_num: '97', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FLEXPWM0_A2/EWM_IN/SPI1_PCS0/FB_AD2, label: LDAC, identifier: LDAC}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "fsl_xbara.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '39', peripheral: ENET, signal: RMII_RXER, pin_signal: PTA5/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/JTAG_TRST_b, pull_select: up}
  - {pin_num: '46', peripheral: ENET, signal: RMII_TXD0, pin_signal: CMP3_IN2/PTA16/SPI0_SOUT/UART0_CTS_b/UART0_COL_b/RMII0_TXD0/MII0_TXD0}
  - {pin_num: '47', peripheral: ENET, signal: RMII_TXD1, pin_signal: HSADC0A_CH15/PTA17/SPI0_SIN/UART0_RTS_b/RMII0_TXD1/MII0_TXD1}
  - {pin_num: '42', peripheral: ENET, signal: RMII_RXD1, pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/RMII0_RXD1/MII0_RXD1/FTM1_QD_PHA/I2C0_SCL, pull_select: up}
  - {pin_num: '43', peripheral: ENET, signal: RMII_RXD0, pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/FTM1_QD_PHB/I2C1_SDA, pull_select: up}
  - {pin_num: '53', peripheral: ENET, signal: RMII_MDIO, pin_signal: HSADC0B_CH2/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA/UART0_RX/RMII0_MDIO/MII0_MDIO, pull_select: up}
  - {pin_num: '54', peripheral: ENET, signal: RMII_MDC, pin_signal: HSADC0B_CH3/PTB1/I2C0_SDA/FTM1_CH1/FTM0_FLT2/EWM_IN/FTM1_QD_PHB/UART0_TX/RMII0_MDC/MII0_MDC, pull_select: up}
  - {pin_num: '44', peripheral: ENET, signal: RMII_CRS_DV, pin_signal: CMP3_IN0/PTA14/SPI0_PCS0/UART0_TX/CAN2_TX/RMII0_CRS_DV/MII0_RXDV/I2C1_SCL, pull_select: up}
  - {pin_num: '45', peripheral: ENET, signal: RMII_TXEN, pin_signal: CMP3_IN1/PTA15/SPI0_SCK/UART0_RX/CAN2_RX/RMII0_TXEN/MII0_TXEN}
  - {pin_num: '1', peripheral: GPIOE, signal: 'GPIO, 0', pin_signal: HSADC0B_CH16/HSADC1A_CH0/PTE0/SPI1_PCS1/UART1_TX/XB_OUT10/XB_IN11/I2C1_SDA/TRACE_CLKOUT}
  - {pin_num: '2', peripheral: SPI1, signal: SOUT, pin_signal: HSADC0B_CH17/HSADC1A_CH1/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/XB_OUT11/XB_IN7/I2C1_SCL/TRACE_D3}
  - {pin_num: '3', peripheral: SPI1, signal: SCK, pin_signal: HSADC0B_CH10/HSADC1B_CH0/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/TRACE_D2}
  - {pin_num: '10', peripheral: HSADC0, signal: 'ADCA, CH0', pin_signal: HSADC0A_CH0/ADC0_SE1/ADC0_DP1/PTE16/SPI0_PCS0/UART2_TX/FTM_CLKIN0/FTM0_FLT3}
  - {pin_num: '12', peripheral: HSADC0, signal: 'ADCB, CH0', pin_signal: HSADC0B_CH0/ADC0_SE5a/PTE18/LLWU_P20/SPI0_SOUT/UART2_CTS_b/I2C0_SDA}
  - {pin_num: '16', peripheral: HSADC0, signal: 'ADCA, CH8', pin_signal: HSADC0A_CH8/ADC0_SE5b/PTE20/FTM1_CH0/UART0_TX/FTM1_QD_PHA}
  - {pin_num: '19', peripheral: HSADC1, signal: 'ADCA, CH3', pin_signal: HSADC0A_CH3/HSADC1A_CH3}
  - {pin_num: '20', peripheral: HSADC1, signal: 'ADCB, CH2', pin_signal: HSADC0A_CH10/HSADC1B_CH2}
  - {pin_num: '26', peripheral: FTM0, signal: 'CH, 2', pin_signal: HSADC0A_CH4/CMP1_IN5/CMP0_IN5/PTE29/FTM0_CH2/FTM_CLKIN0, identifier: M_STEP, direction: OUTPUT}
  - {pin_num: '27', peripheral: GPIOE, signal: 'GPIO, 30', pin_signal: DAC0_OUT/CMP1_IN3/HSADC0A_CH5/PTE30/FTM0_CH3/FTM_CLKIN1, direction: OUTPUT}
  - {pin_num: '31', peripheral: GPIOE, signal: 'GPIO, 24', pin_signal: HSADC0B_CH4/HSADC1B_CH4/PTE24/CAN1_TX/FTM0_CH0/XB_IN2/I2C0_SCL/EWM_OUT_b/XB_OUT4/UART4_TX,
    direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '32', peripheral: GPIOE, signal: 'GPIO, 25', pin_signal: HSADC0B_CH5/HSADC1B_CH5/PTE25/LLWU_P21/CAN1_RX/FTM0_CH1/XB_IN3/I2C0_SDA/EWM_IN/XB_OUT5/UART4_RX,
    direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '33', peripheral: ENET, signal: CLKIN_1588, pin_signal: PTE26/ENET_1588_CLKIN/FTM0_CH4/UART4_CTS_b}
  - {pin_num: '34', peripheral: JTAG, signal: JTAG_TCLK_SWD_CLK, pin_signal: PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/XB_IN4/EWM_IN/JTAG_TCLK/SWD_CLK}
  - {pin_num: '35', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/UART0_RX/FTM0_CH6/CMP0_OUT/FTM2_QD_PHA/FTM1_CH1/JTAG_TDI, identifier: M_EN, direction: OUTPUT,
    gpio_init_state: 'true'}
  - {pin_num: '37', peripheral: JTAG, signal: JTAG_TMS_SWD_DIO, pin_signal: PTA3/UART0_RTS_b/FTM0_CH0/XB_IN9/EWM_OUT_b/FLEXPWM0_A0/JTAG_TMS/SWD_DIO}
  - {pin_num: '50', peripheral: OSC0, signal: EXTAL0, pin_signal: EXTAL0/PTA18/XB_IN7/FTM0_FLT2/FTM_CLKIN0/XB_OUT8/FTM3_CH2}
  - {pin_num: '50', peripheral: ENET, signal: 'RMII_EXTAL, RMII_EXTAL', pin_signal: EXTAL0/PTA18/XB_IN7/FTM0_FLT2/FTM_CLKIN0/XB_OUT8/FTM3_CH2}
  - {pin_num: '68', peripheral: CMP2, signal: OUT, pin_signal: PTB22/SPI2_SOUT/FLEXPWM0_X2/CMP2_OUT/FB_AD29}
  - {pin_num: '69', peripheral: CMP3, signal: OUT, pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FLEXPWM0_X3/CMP3_OUT/FB_AD28}
  - {pin_num: '86', peripheral: PWM1, signal: 'A, 0', pin_signal: PTC14/I2C1_SCL/I2C0_SCL/FLEXPWM1_A0/FB_AD25/UART4_RX}
  - {pin_num: '87', peripheral: PWM1, signal: 'B, 0', pin_signal: PTC15/I2C1_SDA/I2C0_SDA/FLEXPWM1_B0/FB_AD24/UART4_TX}
  - {pin_num: '55', peripheral: CMP2, signal: 'IN, 2', pin_signal: HSADC0A_CH14/CMP2_IN2/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT1/ENET0_1588_TMR0/FTM0_FLT3}
  - {pin_num: '56', peripheral: CMP3, signal: 'IN, 5', pin_signal: HSADC0B_CH15/CMP3_IN5/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0}
  - {pin_num: '51', peripheral: PWM0, signal: 'FAULT, 0', pin_signal: XTAL0/PTA19/XB_IN8/FTM1_FLT0/FTM_CLKIN1/XB_OUT9/LPTMR0_ALT1}
  - {pin_num: '62', peripheral: PWM0, signal: 'FAULT, 1', pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN2/CAN0_TX/EWM_IN/XB_IN5/FB_AD17}
  - {pin_num: '77', peripheral: SPI0, signal: SCK, pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/XB_IN2/CMP0_OUT/FTM0_CH2/FB_AD10}
  - {pin_num: '78', peripheral: SPI0, signal: SOUT, pin_signal: CMP2_IN4/CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/XB_IN3/UART0_RX/XB_OUT6/I2C0_SCL/FB_AD9}
  - {pin_num: '94', peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: HSADC1A_CH11/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FTM0_CH1/FLEXPWM0_B0/FB_CS0_b/FLEXPWM1_B0, direction: INPUT,
    gpio_interrupt: kPORT_InterruptRisingEdge}
  - {pin_num: '95', peripheral: I2C0, signal: SCL, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FTM0_CH2/FLEXPWM0_A1/I2C0_SCL/FB_AD4/FLEXPWM1_A1}
  - {pin_num: '96', peripheral: I2C0, signal: SDA, pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FTM0_CH3/FLEXPWM0_B1/I2C0_SDA/FB_AD3/FLEXPWM1_B1}
  - {pin_num: '99', peripheral: GPIOD, signal: 'GPIO, 6', pin_signal: HSADC1A_CH9/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FTM1_CH0/FTM0_FLT0/SPI1_SOUT/FB_AD0, direction: OUTPUT}
  - {pin_num: '97', peripheral: GPIOD, signal: 'GPIO, 4', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FLEXPWM0_A2/EWM_IN/SPI1_PCS0/FB_AD2, direction: OUTPUT}
  - {pin_num: '82', peripheral: I2C1, signal: SCL, pin_signal: HSADC1B_CH13/PTC10/I2C1_SCL/FTM3_CH6/FLEXPWM1_A3/FB_AD5}
  - {pin_num: '83', peripheral: I2C1, signal: SDA, pin_signal: HSADC1B_CH14/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/FLEXPWM1_B3/FB_RW_b}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Ethernet_pin_init (void)
{
  PORT_SetPinMux(PORTA, PIN12_IDX, kPORT_MuxAlt5);           /* PORTA12 (pin 42) is configured as RMII0_RXD1 */
  PORT_SetPinMux(PORTA, PIN13_IDX, kPORT_MuxAlt5);           /* PORTA13 (pin 43) is configured as RMII0_RXD0 */
  PORT_SetPinMux(PORTA, PIN14_IDX, kPORT_MuxAlt5);           /* PORTA14 (pin 44) is configured as RMII0_CRS_DV */
  PORT_SetPinMux(PORTA, PIN15_IDX, kPORT_MuxAlt5);           /* PORTA15 (pin 45) is configured as RMII0_TXEN */
  PORT_SetPinMux(PORTA, PIN16_IDX, kPORT_MuxAlt5);           /* PORTA16 (pin 46) is configured as RMII0_TXD0 */
  PORT_SetPinMux(PORTA, PIN17_IDX, kPORT_MuxAlt5);           /* PORTA17 (pin 47) is configured as RMII0_TXD1 */
  PORT_SetPinMux(PORTE, PIN26_IDX, kPORT_MuxAlt2);           /* PORTE26 (pin 33) is configured as ENET_1588_CLKIN */
  PORT_SetPinMux(PORTA, PIN5_IDX, kPORT_MuxAsGpio);          /* PORTA5 (pin 39) is configured as kPORT_MuxAsGpio */
  PORT_SetPinMux(PORTB, PIN0_IDX, kPORT_MuxAlt8);            /* PORTB0 (pin 53) is configured as RMII0_MDIO */
  PORT_SetPinMux(PORTB, PIN1_IDX, kPORT_MuxAlt8);            /* PORTB1 (pin 54) is configured as RMII0_MDC */
  
}
void BOARD_InitPins(void)
{
   
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);
    /* XBARA Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_XbarA);

    gpio_pin_config_t M_EN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA1 (pin 35)  */
    GPIO_PinInit(BOARD_INITPINS_M_EN_GPIO, BOARD_INITPINS_M_EN_PIN, &M_EN_config);

   gpio_pin_config_t RES_PHY_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB9 (pin 57)  */
    GPIO_PinInit(BOARD_INITPINS_RES_PHY_GPIO, BOARD_INITPINS_RES_PHY_PIN, &RES_PHY_config);


    gpio_pin_config_t LED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC13 (pin 85)  */
    GPIO_PinInit(BOARD_INITPINS_LED_GPIO, BOARD_INITPINS_LED_PIN, &LED_config);

    
            PORTC->PCR[2] = ((PORTC->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullDisable)

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));
    
    
    
    
    gpio_pin_config_t OVER_T_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD1 (pin 94)  */
    GPIO_PinInit(BOARD_INITPINS_OVER_T_GPIO, BOARD_INITPINS_OVER_T_PIN, &OVER_T_config);

    gpio_pin_config_t LDAC_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD4 (pin 97)  */
    GPIO_PinInit(BOARD_INITPINS_LDAC_GPIO, BOARD_INITPINS_LDAC_PIN, &LDAC_config);

    gpio_pin_config_t DRV_OFF_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD6 (pin 99)  */
    GPIO_PinInit(BOARD_INITPINS_DRV_OFF_GPIO, BOARD_INITPINS_DRV_OFF_PIN, &DRV_OFF_config);
    
    
 gpio_pin_config_t BUS_kontaktor_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE0 (pin 1)  */
    GPIO_PinInit(BOARD_INITPINS_BUS_kontaktor_GPIO, BOARD_INITPINS_BUS_kontaktor_PIN, &BUS_kontaktor_config);
 
    gpio_pin_config_t M_RES_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE24 (pin 31)  */
    GPIO_PinInit(BOARD_INITPINS_M_RES_GPIO, BOARD_INITPINS_M_RES_PIN, &M_RES_config);

    gpio_pin_config_t M_SLEEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE25 (pin 32)  */
    GPIO_PinInit(BOARD_INITPINS_M_SLEEP_GPIO, BOARD_INITPINS_M_SLEEP_PIN, &M_SLEEP_config);

    gpio_pin_config_t M_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE30 (pin 27)  */
    GPIO_PinInit(BOARD_INITPINS_M_DIR_GPIO, BOARD_INITPINS_M_DIR_PIN, &M_DIR_config);

////    /* PORTA0 (pin 34) is configured as JTAG_TCLK */
////    PORT_SetPinMux(PORTA, 0U, kPORT_MuxAlt7);

    /* PORTA1 (pin 35) is configured as PTA1 */
    PORT_SetPinMux(BOARD_INITPINS_M_EN_PORT, BOARD_INITPINS_M_EN_PIN, kPORT_MuxAsGpio);

    /* PORTA12 (pin 42) is configured as RMII0_RXD1 */
    PORT_SetPinMux(PORTA, 12U, kPORT_MuxAlt5);

    PORTA->PCR[12] = ((PORTA->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTA13 (pin 43) is configured as RMII0_RXD0 */
    PORT_SetPinMux(PORTA, 13U, kPORT_MuxAlt5);

    PORTA->PCR[13] = ((PORTA->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTA14 (pin 44) is configured as RMII0_CRS_DV */
    PORT_SetPinMux(PORTA, 14U, kPORT_MuxAlt5);

    PORTA->PCR[14] = ((PORTA->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTA15 (pin 45) is configured as RMII0_TXEN */
    PORT_SetPinMux(PORTA, 15U, kPORT_MuxAlt5);

    /* PORTA16 (pin 46) is configured as RMII0_TXD0 */
    PORT_SetPinMux(PORTA, 16U, kPORT_MuxAlt5);

    /* PORTA17 (pin 47) is configured as RMII0_TXD1 */
    PORT_SetPinMux(PORTA, 17U, kPORT_MuxAlt5);

    /* PORTA18 (pin 50) is configured as EXTAL0 */
    PORT_SetPinMux(PORTA, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTA19 (pin 51) is configured as XB_IN8 */
    PORT_SetPinMux(PORTA, 19U, kPORT_MuxAlt2);
    
    
    gpio_pin_config_t DRV_TCLK_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB10 (pin 58)  */
    GPIO_PinInit(BOARD_INITPINS_DRV_XLAT_GPIO, BOARD_INITPINS_DRV_XLAT_PIN, &DRV_TCLK_config);
/* PORTB10 (pin 58) is configured as PTB10 */
    PORT_SetPinMux(BOARD_INITPINS_DRV_XLAT_PORT, BOARD_INITPINS_DRV_XLAT_PIN, kPORT_MuxAsGpio);

////    /* PORTA3 (pin 37) is configured as JTAG_TMS */
////    PORT_SetPinMux(PORTA, 3U, kPORT_MuxAlt7);

    /* PORTA5 (pin 39) is configured as RMII0_RXER */
    PORT_SetPinMux(PORTA, 5U, kPORT_MuxAlt4);

    PORTA->PCR[5] = ((PORTA->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB0 (pin 53) is configured as RMII0_MDIO */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAlt8);

    PORTB->PCR[0] = ((PORTB->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB1 (pin 54) is configured as RMII0_MDC */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAlt8);

    PORTB->PCR[1] = ((PORTB->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB16 (pin 62) is configured as XB_IN5 */
    PORT_SetPinMux(PORTB, 16U, kPORT_MuxAlt7);

    /* PORTB2 (pin 55) is configured as CMP2_IN2 */
    PORT_SetPinMux(PORTB, 2U, kPORT_PinDisabledOrAnalog);

    /* PORTB22 (pin 68) is configured as CMP2_OUT */
    PORT_SetPinMux(PORTB, 22U, kPORT_MuxAlt6);

    /* PORTB23 (pin 69) is configured as CMP3_OUT */
    PORT_SetPinMux(PORTB, 23U, kPORT_MuxAsGpio);

gpio_pin_config_t OUT_CMP3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB23 (pin 69)  */
    GPIO_PinInit(BOARD_INITPINS_OUT_CMP3_GPIO, BOARD_INITPINS_OUT_CMP3_PIN, &OUT_CMP3_config);
    
    

    /* PORTB3 (pin 56) is configured as CMP3_IN5 */
    PORT_SetPinMux(PORTB, 3U, kPORT_PinDisabledOrAnalog);
     /* PORTB9 (pin 57) is configured as PTB9 */
    PORT_SetPinMux(BOARD_INITPINS_RES_PHY_PORT, BOARD_INITPINS_RES_PHY_PIN, kPORT_MuxAsGpio);


//////    /* PORTC10 (pin 82) is configured as I2C1_SCL */
//////    PORT_SetPinMux(PORTC, 10U, kPORT_MuxAlt2);
//////
//////    PORTC->PCR[10] = ((PORTC->PCR[10] &
//////                       /* Mask bits to zero which are setting */
//////                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))
//////
//////                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
//////                       * corresponding PE field is set. */
//////                      | (uint32_t)(kPORT_PullUp)
//////
//////                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
//////                       * configured as a digital output. */
//////                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));
//////
//////    /* PORTC11 (pin 83) is configured as I2C1_SDA */
//////    PORT_SetPinMux(PORTC, 11U, kPORT_MuxAlt2);
//////
//////    PORTC->PCR[11] = ((PORTC->PCR[11] &
//////                       /* Mask bits to zero which are setting */
//////                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))
//////
//////                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
//////                       * corresponding PE field is set. */
//////                      | (uint32_t)(kPORT_PullUp)
//////
//////                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
//////                       * configured as a digital output. */
//////                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

 const port_pin_config_t portd8_pin82_config = {/* Internal pull-up resistor is enabled */
                                                    kPORT_PullUp,
                                                    /* Fast slew rate is configured */
                                                    kPORT_FastSlewRate,
                                                    /* Passive filter is disabled */
                                                    kPORT_PassiveFilterDisable,
                                                    /* Open drain is enabled */
                                                    kPORT_OpenDrainEnable,
                                                    /* Low drive strength is configured */
                                                    kPORT_LowDriveStrength,
                                                    /* Pin is configured as I2C1_SCL */
                                                    kPORT_MuxAlt2,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    kPORT_UnlockRegister};
    /* PORTD8 (pin 137) is configured as I2C1_SCL */
    PORT_SetPinConfig(PORTC, 10U, &portd8_pin82_config);

    const port_pin_config_t portd9_pin83_config = {/* Internal pull-up resistor is enabled */
                                                    kPORT_PullUp,
                                                    /* Fast slew rate is configured */
                                                    kPORT_FastSlewRate,
                                                    /* Passive filter is disabled */
                                                    kPORT_PassiveFilterDisable,
                                                    /* Open drain is enabled */
                                                    kPORT_OpenDrainEnable,
                                                    /* Low drive strength is configured */
                                                    kPORT_LowDriveStrength,
                                                    /* Pin is configured as I2C1_SDA */
                                                    kPORT_MuxAlt2,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    kPORT_UnlockRegister};
    /* PORTD9 (pin 138) is configured as I2C1_SDA */
    PORT_SetPinConfig(PORTC, 11U, &portd9_pin83_config);
    
      /* PORTC12 (pin 84) is configured as PTC13 */
    PORT_SetPinMux(BOARD_INITPINS_DRV_XLAT_PORT, BOARD_INITPINS_DRV_XLAT_PIN, kPORT_MuxAsGpio);
    
      PORTC->PCR[12] = ((PORTC->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainDisable));
      
      
    
    /* PORTC13 (pin 85) is configured as PTC13 */
    PORT_SetPinMux(BOARD_INITPINS_LED_PORT, BOARD_INITPINS_LED_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[13] = ((PORTC->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTC14 (pin 86) is configured as FLEXPWM1_A0 */
    PORT_SetPinMux(BOARD_INITPINS_HI_SWICH_PORT, BOARD_INITPINS_HI_SWICH_PIN, kPORT_MuxAlt5);

    /* PORTC15 (pin 87) is configured as FLEXPWM1_B0 */
    PORT_SetPinMux(BOARD_INITPINS_LO_SWICH_PORT, BOARD_INITPINS_LO_SWICH_PIN, kPORT_MuxAlt5);
    /* PORTC2 (pin 72) is configured as FTM0_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_CLK_OUT_PORT, BOARD_INITPINS_CLK_OUT_PIN, kPORT_MuxAlt4);
        /* PORTC3 (pin 73) is configured as CLKOUT */
    PORT_SetPinMux(PORTC, 3U, kPORT_MuxAlt5);
    
    /* PORTC5 (pin 77) is configured as SPI0_SCK */
    PORT_SetPinMux(BOARD_INITPINS_CONF_CLK_PORT, BOARD_INITPINS_CONF_CLK_PIN, kPORT_MuxAlt2);
     
    
    PORTC->PCR[5] = ((PORTC->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Enable: Internal pullup or pulldown resistor is enabled on the corresponding pin. */
                     | (uint32_t)(PORT_PCR_PE_MASK));
    
    
    /* PORTC6 (pin 78) is configured as SPI0_SOUT */
    PORT_SetPinMux(BOARD_INITPINS_CONF_SO_PORT, BOARD_INITPINS_CONF_SO_PIN, kPORT_MuxAlt2);

    /* PORTD1 (pin 94) is configured as PTD1 */
    PORT_SetPinMux(BOARD_INITPINS_OVER_T_PORT, BOARD_INITPINS_OVER_T_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD1 (pin 94): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_OVER_T_PORT, BOARD_INITPINS_OVER_T_PIN, kPORT_InterruptRisingEdge);
    
     const port_pin_config_t portd3_pin96_config = {/* Internal pull-up resistor is enabled */
                                                    kPORT_PullUp,
                                                    /* Fast slew rate is configured */
                                                    kPORT_FastSlewRate,
                                                    /* Passive filter is disabled */
                                                    kPORT_PassiveFilterDisable,
                                                    /* Open drain is enabled */
                                                    kPORT_OpenDrainEnable,
                                                    /* Low drive strength is configured */
                                                    kPORT_LowDriveStrength,
                                                    /* Pin is configured as I2C1_SCL */
                                                    kPORT_MuxAlt7,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    kPORT_UnlockRegister};
    
     PORT_SetPinConfig(PORTD, 3U, &portd3_pin96_config);

    const port_pin_config_t portd2_pin95_config = {/* Internal pull-up resistor is enabled */
                                                    kPORT_PullUp,
                                                    /* Fast slew rate is configured */
                                                    kPORT_FastSlewRate,
                                                    /* Passive filter is disabled */
                                                    kPORT_PassiveFilterDisable,
                                                    /* Open drain is enabled */
                                                    kPORT_OpenDrainEnable,
                                                    /* Low drive strength is configured */
                                                    kPORT_LowDriveStrength,
                                                    /* Pin is configured as I2C1_SDA */
                                                    kPORT_MuxAlt7,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    kPORT_UnlockRegister};
    
    PORT_SetPinConfig(PORTD, 2U, &portd2_pin95_config);
    
    
////////
////////    /* PORTD2 (pin 95) is configured as I2C0_SCL */
////////    PORT_SetPinMux(PORTD, 2U, kPORT_MuxAlt7);
////////
////////    PORTD->PCR[2] = ((PORTD->PCR[2] &
////////                      /* Mask bits to zero which are setting */
////////                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))
////////
////////                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
////////                      * corresponding PE field is set. */
////////                     | (uint32_t)(kPORT_PullUp)
////////
////////                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
////////                      * configured as a digital output. */
////////                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));
////////
////////    /* PORTD3 (pin 96) is configured as I2C0_SDA */
////////    PORT_SetPinMux(PORTD, 3U, kPORT_MuxAlt7);
////////
////////    PORTD->PCR[3] = ((PORTD->PCR[3] &
////////                      /* Mask bits to zero which are setting */
////////                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))
////////
////////                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
////////                      * corresponding PE field is set. */
////////                     | (uint32_t)(kPORT_PullUp)
////////
////////                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
////////                      * configured as a digital output. */
////////                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));
    /* PORTD4 (pin 97) is configured as PTD4 */
    PORT_SetPinMux(BOARD_INITPINS_LDAC_PORT, BOARD_INITPINS_LDAC_PIN, kPORT_MuxAsGpio);

    /* PORTD6 (pin 99) is configured as PTD6 */
    PORT_SetPinMux(BOARD_INITPINS_DRV_OFF_PORT, BOARD_INITPINS_DRV_OFF_PIN, kPORT_MuxAsGpio);
    
    PORTD->PCR[6] = ((PORTD->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));

   /* PORTE0 (pin 1) is configured as PTE0 */
    PORT_SetPinMux(BOARD_INITPINS_BUS_kontaktor_PORT, BOARD_INITPINS_BUS_kontaktor_PIN, kPORT_MuxAsGpio);


  /* PORTE1 (pin 2) is configured as SPI1_SOUT */
    PORT_SetPinMux(BOARD_INITPINS_DRV_SO_PORT, BOARD_INITPINS_DRV_SO_PIN, kPORT_MuxAlt2);
////    
////     PORTE->PCR[3] = ((PORTE->PCR[3] &
////                      /* Mask bits to zero which are setting */
////                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))
////
////                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
////                      * corresponding PE field is set. */
////                     | (uint32_t)(kPORT_PullDisable)
////
////                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
////                      * configured as a digital output. */
////                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));
    
  /* PORTE2 (pin 3) is configured as SPI1_SCK */
    PORT_SetPinMux(BOARD_INITPINS_DRV_CLK_PORT, BOARD_INITPINS_DRV_CLK_PIN, kPORT_MuxAlt2);
    
    
////        PORTE->PCR[2] = ((PORTE->PCR[2] &
////                      /* Mask bits to zero which are setting */
////                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))
////
////                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
////                      * corresponding PE field is set. */
////                     | (uint32_t)(kPORT_PullDisable)
////
////                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
////                      * configured as a digital output. */
////                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));
////    
    

        
        
    /* PORTE16 (pin 10) is configured as HSADC0A_CH0 */
    PORT_SetPinMux(PORTE, 16U, kPORT_PinDisabledOrAnalog);

    /* PORTE18 (pin 12) is configured as HSADC0B_CH0 */
    PORT_SetPinMux(PORTE, 18U, kPORT_PinDisabledOrAnalog);

 
    /* PORTE20 (pin 16) is configured as HSADC0A_CH8 */
    PORT_SetPinMux(PORTE, 20U, kPORT_PinDisabledOrAnalog);

    /* PORTE24 (pin 31) is configured as PTE24 */
    PORT_SetPinMux(BOARD_INITPINS_M_RES_PORT, BOARD_INITPINS_M_RES_PIN, kPORT_MuxAsGpio);

    /* PORTE25 (pin 32) is configured as PTE25 */
    PORT_SetPinMux(BOARD_INITPINS_M_SLEEP_PORT, BOARD_INITPINS_M_SLEEP_PIN, kPORT_MuxAsGpio);

    /* PORTE26 (pin 33) is configured as ENET_1588_CLKIN */
    PORT_SetPinMux(PORTE, 26U, kPORT_MuxAlt2);
    
    /* PORTE3 (pin 4) is configured as SPI1_SIN */
    PORT_SetPinMux(PORTE, 3U, kPORT_MuxAlt2);

    /* PORTE29 (pin 26) is configured as FTM0_CH2 */
    PORT_SetPinMux(BOARD_INITPINS_M_STEP_PORT, BOARD_INITPINS_M_STEP_PIN, kPORT_MuxAlt3);

    /* PORTE30 (pin 27) is configured as PTE30 */
    PORT_SetPinMux(BOARD_INITPINS_M_DIR_PORT, BOARD_INITPINS_M_DIR_PIN, kPORT_MuxAsGpio);

    SIM->SOPT2 = ((SIM->SOPT2 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT2_RMIISRC_MASK | SIM_SOPT2_TIMESRC_MASK)))

                  /* RMII clock source select: EXTAL clock. */
                  | SIM_SOPT2_RMIISRC(SOPT2_RMIISRC_EXTAL)

                  /* IEEE 1588 timestamp clock source select: External bypass clock (ENET_1588_CLKIN). */
                  | SIM_SOPT2_TIMESRC(SOPT2_TIMESRC_ENET));

    SIM->SOPT8 = ((SIM->SOPT8 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT8_FTM0OCH1SRC_MASK | SIM_SOPT8_FTM0OCH2SRC_MASK)))

                  /* FTM0 channel 1 output source: FTM0_CH1 pin is output of FTM0 channel 1 output. */
                  | SIM_SOPT8_FTM0OCH1SRC(SOPT8_FTM0OCH1SRC_FTM)

                  /* FTM0 channel 2 output source: FTM0_CH2 pin is output of FTM0 channel 2 output. */
                  | SIM_SOPT8_FTM0OCH2SRC(SOPT8_FTM0OCH2SRC_FTM));
    
    
    /* XB_IN8 input pin output assigned to XBARA_IN8 input is connected
     * to XBARA_OUT29 output assigned to PWM0 and PWM1 fault 0 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbarIn8, kXBARA_OutputPwm0Fault0);
    /* XB_IN5 input pin output assigned to XBARA_IN5 input is connected
     * to XBARA_OUT30 output assigned to PWM0 and PWM1 fault 1 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbarIn5, kXBARA_OutputPwm0Fault1);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
